defaults:
  - task_config_base
  - measurements:
    - distance_to_goal
    - distance_to_goal_reward
    - success 
    - did_multi_agents_collide 
    - num_steps 
    - top_down_map
    - spl
    - psc
    - stl
    - human_collision
    - human_velocity_measure # for orca
  - lab_sensors:
    - localization_sensor 
    - oracle_shortest_path_sensor # for astar
    - human_velocity_sensor # for orca
  - _self_

type: MultiAgentPointNavTask-v0
end_on_success: True
reward_measure: "distance_to_goal_reward"
success_measure: "spl"
success_reward: 10.0
slack_reward: -0.002
goal_sensor_uuid: pointgoal_with_gps_compass